FROM golang:buster AS development

# We need to use Buster as Alpine removed `qsort` lib that is used by the forwarder

   
# Building the multi chan packet forwarder for RAK2245
RUN git clone https://github.com/Lora-net/lora_gateway \
    # lowering the SPI speed for more reliability
    && sed -i -- 's/SPI_SPEED.*8000000/SPI_SPEED 1000000/g' ./lora_gateway/libloragw/src/loragw_spi.native.c \
    && git clone https://github.com/Lora-net/packet_forwarder \
    && cd packet_forwarder \
    && ./compile.sh

# Building the single chan packet forwarder for WAziHat
RUN git clone https://github.com/Waziup/single_chan_pkt_fwd \
    && cd single_chan_pkt_fwd \
    && go build -o build/single_chan_pkt_fwd .

# Building the multi chan packet forwarder for USB HT-M01
RUN git clone https://github.com/Lora-net/picoGW_hal.git \
    && cd picoGW_hal \
    && make \
    && cd .. \
    && git clone https://github.com/Lora-net/picoGW_packet_forwarder.git \
    && cd picoGW_packet_forwarder \
    && make
    

COPY  packet_forwarder/lora_pkt_fwd/lora_pkt_fwd        /root/spi_multi_chan/lora_pkt_fwd
COPY  lora_gateway/reset_lgw.sh                         /root/spi_multi_chan/reset_lgw.sh
COPY  single_chan_pkt_fwd/build/single_chan_pkt_fwd     /root/single_chan/lora_pkt_fwd
COPY  picoGW_packet_forwarder/lora_pkt_fwd/lora_pkt_fwd /root/usb_multi_chan/lora_pkt_fwd
COPY ./start.sh /root/

ENTRYPOINT ["tail", "-f", "/dev/null"]
